# Generated by Django 4.2.1 on 2023-05-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='iva',
            new_name='igv',
        ),
    ]
