# Generated by Django 4.2.1 on 2023-05-06 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_rename_iva_factura_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
